### ISSUE TITLE
Centering the profile-mode

### ISSUE THREAD

**Issue by joelsleeba** [pmichaillat/pmichaillat.github.io#1]
Hey, love the customization you did to papermod. I was adopting some of the changes you implemented and noticed that the profile class max-height was supposed to fill the viewport height in the original papermod theme. But since the header and footer was removed in your customization, it needs to be removed max-height property of the profile class for a true centering.
I don't know if this was intentional or something that you missed. Checkout what I did in [my page](joelsleeba.github.io/blog).

**Comment by pmichaillat** [comment]
Hi Joel, thank you so much for reporting this issue. This is indeed something that I missed. I have used your code to fix the centering. Thanks again!
